name: CI - Linux

on:
  push:
    branches: [ stable0 ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install \
          g++-8 \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libc-ares-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev
    - name: Setup gcc
      run: |
        echo 'CC=gcc-8' >> $GITHUB_ENV
        echo 'CXX=g++-8' >> $GITHUB_ENV
    - name: Libtool
      run: |
        autoreconf -i
    - name: Configure autotools
      run: |
        ./configure \
          CPPFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
    - name: Build aria2
      run: |
        make
        make check
    - name: Check
      run: ls
    - uses: actions/upload-artifact@v3
      with:
        name: Upload artifact
        path: ./aria2c
